server:
  port: 8870

spring:
  application:
    name: gmall-search
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.188.100:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false