server:
  port: 88

spring:
  application:
    name: gmall-gateway
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://gmall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
    nacos:
      discovery:
        server-addr: 192.168.188.100:8848